---
version: "3"

services:
  site:
    command: jekyll serve --incremental
    image: jekyll/jekyll
    volumes:
      - ./:/srv/jekyll:delegated
      - ./vendor/bundle:/usr/local/bundle:delegated
    ports:
      - 4000:4000